name: StreamplaceTV
options:
  bundleIdPrefix: tv.aquareum
  deploymentTarget:
    tvOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ${SP_APPLE_TEAM_ID}
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  StreamplaceTV:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: StreamplaceTV
        excludes:
          - "**/Info.plist"
    resources:
      - StreamplaceTV/Resources/Assets.xcassets
    info:
      path: StreamplaceTV/Resources/Info.plist
      properties:
        CFBundleDisplayName: Streamplace
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UIRequiredDeviceCapabilities:
          - arm64
        UILaunchStoryboardName: ""
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIUserInterfaceStyle: Automatic
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tv.aquareum.tv
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "3"
        TVOS_DEPLOYMENT_TARGET: "17.0"
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        SUPPORTS_MACCATALYST: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SDKROOT: appletvos
        ENABLE_PREVIEWS: "YES"
